name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Bootstrap
        run: make bootstrap
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGES_TOKEN }}

      - name: Publish Packages
        run: make publish --jobs=2
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
